# Generated by Django 3.2.6 on 2021-08-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("majors", "0002_alter_collegemajor_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="major",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
