# Generated by Django 3.2.6 on 2021-08-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("majors", "0003_major_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collegemajor",
            options={"ordering": ["college", "major"]},
        ),
    ]
