# Generated by Django 3.2.6 on 2021-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
