# Generated by Django 3.2.6 on 2021-08-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0002_college_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="slug",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
