# Generated by Django 3.2.6 on 2021-08-26 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0004_auto_20210826_1028"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("pre_reqs", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True, max_length=200)),
                ("course_outcomes", models.TextField(blank=True, max_length=200)),
                ("URL", models.URLField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colleges.college",
                    ),
                ),
            ],
        ),
    ]
