# Generated by Django 3.2.6 on 2021-08-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
