# Generated by Django 3.2.6 on 2021-08-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_credits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_outcomes",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
