# Generated by Django 3.2.6 on 2021-08-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_auto_20210829_2124"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursetype", options={"ordering": ["order"]},
        ),
    ]
