# Generated by Django 3.2.6 on 2021-08-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_coursetype_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_outcomes",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
